# 站点配置： 可以通过 {{ site.变量名 }} 获取对应的值
title: 檐下赏月编码 
email: vran@vip.qq.com
url: "https://blog.cc1234.cc"
github_username: vran-dev 
description: >- # this means to ignore newlines until "baseurl:"
    Java, TCP, OS, Scala
baseurl: "" # the subpath of your site, e.g. /blog

# 集合相关配置
collections:
  articles:
    output: true

# markdown渲染
markdown: kramdown

# 配置 articles/ 下的文章默认属性
defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
      author: "vran"

# 插件
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
